# Generated by Django 5.2.17 on 2026-09-10 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folder", models.CharField(db_index=True, max_length=255)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("ok", models.BooleanField(default=False)),
                ("rounds_imported", models.IntegerField(default=0)),
                ("message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_id", models.CharField(max_length=64, unique=True)),
                ("folder", models.CharField(max_length=255)),
                ("source_path", models.TextField(blank=True)),
                ("played_at", models.DateTimeField(db_index=True)),
                ("map_id", models.BigIntegerField(default=0)),
                ("map_name", models.CharField(db_index=True, max_length=64)),
                ("map_slug", models.CharField(db_index=True, max_length=64)),
                ("match_type", models.CharField(blank=True, max_length=32)),
                ("gamemode", models.CharField(blank=True, max_length=32)),
                ("game_version", models.CharField(blank=True, max_length=32)),
                ("code_version", models.BigIntegerField(default=0)),
                ("rounds_count", models.IntegerField(default=0)),
                ("my_team_index", models.IntegerField(default=0)),
                ("my_score", models.IntegerField(default=0)),
                ("opponent_score", models.IntegerField(default=0)),
                ("won", models.BooleanField(blank=True, null=True)),
                ("parsed_at", models.DateTimeField(auto_now=True)),
                ("parser_version", models.CharField(blank=True, max_length=16)),
                ("warnings", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name_plural": "matches",
                "ordering": ["-played_at"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_id", models.CharField(max_length=64, unique=True)),
                ("username", models.CharField(db_index=True, max_length=64)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("is_me", models.BooleanField(db_index=True, default=False)),
                ("first_seen", models.DateTimeField(blank=True, null=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["username"],
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("overtime_number", models.IntegerField(default=0)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("site", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "my_side",
                    models.CharField(
                        blank=True,
                        choices=[("Attack", "Ataque"), ("Defense", "Defensa")],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                ("my_team_won", models.BooleanField(blank=True, null=True)),
                ("win_condition", models.CharField(blank=True, max_length=32)),
                ("win_condition_certain", models.BooleanField(default=True)),
                ("score_before", models.JSONField(blank=True, default=list)),
                ("score_after", models.JSONField(blank=True, default=list)),
                ("clock_start", models.FloatField(default=0)),
                ("clock_end", models.FloatField(default=0)),
                ("possible_plant", models.BooleanField(default=False)),
                ("teams", models.JSONField(blank=True, default=list)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="replays.match",
                    ),
                ),
            ],
            options={
                "ordering": ["match__played_at", "number"],
                "unique_together": {("match", "number")},
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("kind", models.CharField(db_index=True, max_length=32)),
                ("clock", models.FloatField(default=0)),
                ("clock_raw", models.CharField(blank=True, max_length=16)),
                ("elapsed", models.FloatField(default=0)),
                ("actor_name", models.CharField(blank=True, max_length=64)),
                ("target_name", models.CharField(blank=True, max_length=64)),
                ("headshot", models.BooleanField(blank=True, null=True)),
                ("operator", models.CharField(blank=True, max_length=32)),
                ("message", models.TextField(blank=True)),
                ("traded", models.BooleanField(default=False)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_as_actor",
                        to="replays.player",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_as_target",
                        to="replays.player",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="replays.round",
                    ),
                ),
            ],
            options={
                "ordering": ["round", "order"],
            },
        ),
        migrations.CreateModel(
            name="RoundPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=64)),
                ("team_index", models.IntegerField(default=0)),
                (
                    "side",
                    models.CharField(
                        blank=True,
                        choices=[("Attack", "Ataque"), ("Defense", "Defensa")],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                ("is_me", models.BooleanField(db_index=True, default=False)),
                ("won", models.BooleanField(default=False)),
                ("operator_id", models.BigIntegerField(default=0)),
                (
                    "operator",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("spawn", models.CharField(blank=True, max_length=64)),
                ("kills", models.IntegerField(default=0)),
                ("died", models.BooleanField(default=False)),
                ("headshots", models.IntegerField(default=0)),
                ("assists", models.IntegerField(default=0)),
                ("score", models.IntegerField(default=0)),
                ("one_vx", models.IntegerField(default=0)),
                ("opening_kill", models.BooleanField(default=False)),
                ("opening_death", models.BooleanField(default=False)),
                ("entry_kill", models.BooleanField(default=False)),
                ("trade_kills", models.IntegerField(default=0)),
                ("was_traded", models.BooleanField(default=False)),
                ("untraded_death", models.BooleanField(default=False)),
                ("death_clock", models.FloatField(blank=True, null=True)),
                ("death_elapsed", models.FloatField(blank=True, null=True)),
                ("survived", models.BooleanField(default=False)),
                ("kst", models.BooleanField(default=False)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="replays.player",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="replays.round",
                    ),
                ),
            ],
            options={
                "ordering": ["round", "team_index", "-kills"],
                "indexes": [
                    models.Index(
                        fields=["is_me", "side"], name="replays_rou_is_me_c1477f_idx"
                    ),
                    models.Index(
                        fields=["is_me", "operator"],
                        name="replays_rou_is_me_d222cf_idx",
                    ),
                ],
                "unique_together": {("round", "player")},
            },
        ),
    ]
