# Generated by Django 5.2.18 on 2026-10-07 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("replays", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUbisoft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datos", models.JSONField(default=dict)),
                ("consultado", models.DateTimeField()),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_ubisoft",
                        to="replays.player",
                    ),
                ),
            ],
        ),
    ]
